name: build

on:
  push:
    branches:
      - master
      - "*-stable"
      - "*/ci-check"
  pull_request:
    branches:
      - master

jobs:
  rspec:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ 2.7, 2.6, 2.5 ]

    runs-on: ${{ matrix.os }}

    env:
      OPAL_VERSION: ${{ matrix.opal }}

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: {ruby-version: "${{ matrix.ruby }}"}
      - run: bin/setup
      - run: bin/rake rspec

  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: {ruby-version: 2.7}
      - run: bin/setup
      - run: bin/rake lint





# name: Ruby
#
# on:
#   push:
#     branches:
#       - master
#       - "*/ci-check"
#       - "*-stable"
#   pull_request:
#     branches:
#       - master
#
# env:
#   BUNDLE_JOBS: 3
#   BUNDLE_RETRY: 3
#   BUNDLE_PATH: vendor/bundle
#
# jobs:
#   latest-ruby:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-ruby@v1
#       with: {ruby-version: "2.6.x"}
#
#     # Checkout
#     - run: git config --global core.autocrlf false
#     - uses: actions/cache@v1
#       with: {path: ".git", key: "git-modules-v4-${{ github.ref }}"}
#     - run: |
#         auth_header="$(git config --local --get http.https://github.com/.extraheader)"
#         git submodule sync --recursive
#         git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
#
#     # Ruby deps
#     - run: gem install bundler --conservative
#     - uses: actions/cache@v1
#       with:
#         path: vendor/bundle
#         key: ruby-deps-v1-${{ runner.os }}-${{ github.ref }}
#         restore-keys: |
#           ruby-deps-v1-${{ runner.os }}-${{ github.ref }}
#           ruby-deps-v1-${{ runner.os }}-master
#           ruby-deps-v1-
#     - run: bundle install
#
#     # JS deps
#     - uses: actions/setup-node@v1
#       with:
#         node-version: '10.x'
#     - uses: actions/cache@v1
#       with:
#         path: node_modules
#         key: javascript-deps-v1-${{ runner.os }}
#     - uses: actions/cache@v1
#       with:
#         path: package.json
#         key: javascript-deps-v1-package-json-${{ runner.os }}
#     - uses: actions/cache@v1
#       with:
#         path: package-lock.json
#         key: javascript-deps-v1-package-lock-json-${{ runner.os }}
#     - run: npm install jshint uglify-js
#
#     # Test
#     - run: bundle exec rake



# --- TRAVIS


# language: ruby
#
# # https://github.com/discourse/mini_racer#travis-ci
# sudo: required
# dist: trusty
#
# addons:
#   chrome: stable
#
# git:
#   submodules: false
#
# branches:
#   only:
#   - master
#   - /^.*-stable$/
#   - /^.*ci-check$/
#
# cache:
#   bundler: true
#   directories:
#     - /home/travis/.nvm/
#     - smoke_test_opal_rspec
#     - node_modules
#
# matrix:
#   fast_finish: true
#
#   include:
#     - rvm: jruby-9.2
#       env:
#         - RUN=rspec
#         - JRUBY_OPTS=--dev
#
#     - rvm: 2.6
#       env: RUN=mspec_opal_chrome
#
#     - rvm: 2.6
#       env: RUN=mspec_ruby_chrome
#
#     # - rvm: 2.6
#     #   env:
#     #     - RUN=browser_test
#     #     - SAUCE_USERNAME=elia
#     #     # SAUCE_ACCESS_KEY:
#     #     - secure: GT13SjzU8vmqKIyY2LAXje+ndqevTsX/w71JkZHRLTrDUl0qcIod7xsfahbzGt2gOZPYZUkKiVaPoUenhc/YeJ2jTJVHeHY9UEl2II+3tOtuvp2jLadA//aBbsB6/09d7lIZMzpa93TL2R/SncPxugYW9v2o8o8Lwd2iIzowT/g=
#
#     - rvm: 2.6
#       env: RUN=lint
#
#     - rvm: 2.6
#       env: RUN=mspec_opal_nodejs
#
#     - rvm: 2.6
#       env: RUN=mspec_ruby_nodejs TZ="/usr/share/zoneinfo/Pacific/Fiji"
#
#     - rvm: 2.6
#       env: RUN=minitest
#
#     - rvm: 2.6
#       env: RUN=rspec RACK_VERSION='~> 2.0' CHECK_COVERAGE=true
#
#     - rvm: 2.6
#       env: RUN=smoke_test
#
#     - rvm: ruby-head
#       env: RUN=rspec
#
#     - rvm: 2.5
#       env: RUN=rspec RACK_VERSION='~> 2.0'
#
#     - rvm: 2.4
#       env: RUN=rspec
#
#     - rvm: 2.7
#       env: RUN=rspec
#
#     - rvm: truffleruby
#       env: RUN=rspec
#
#     - rvm: jruby-head
#       env:
#         - RUN=rspec
#         - JRUBY_OPTS=--dev
#
#   allow_failures:
#     - rvm: ruby-head
#     - rvm: jruby-head
#     - rvm: truffleruby
#     - env: RUN=smoke_test
#
# before_install:
#   # Keep track of which version of node we're running the specs against
#   - bin/git-submodule-fast-install
#   - node -v
#   - npm install
#   - export PATH="node_modules/.bin:$PATH"
#   - bundle config without doc
#   - which google-chrome-stable
#   - google-chrome-stable --version
#   - export RUBYOPT=-w
#   # Workaround from https://github.com/travis-ci/travis-ci/issues/9024#issuecomment-356282802
#   - sudo chown root /opt/google/chrome/chrome-sandbox
#   - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
#
# script:
#   - "bundle exec rake $RUN"



# --- APPVEYOR

# version: '{build}'
#
# skip_tags: true
#
# clone_depth: 10
#
# environment:
#   ruby_version: '25'
#   nodejs_version: '12'
#
# branches:
#   only:
#     - master
#     - /.*-stable/
#     - /.*/ci-check/
#
# cache:
#   - smoke_test_opal_rspec
#   - node_modules
#   - '%APPDATA%\npm-cache'
#
# install:
#   # Install node
#   - ps: Install-Product node $env:nodejs_version
#   # Take default Ruby out of path
#   - SET PATH=%PATH:C:\Ruby193\bin;=%
#   # Add Ruby to path from build matrix
#   - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
#   - ruby --version
#   - gem --version
#   - node --version
#   - bundler --version
#   - bundle
#   - ruby bin/git-submodule-fast-install
#   - npm install
#
# build: off
#
# # TODO: add mspec_chrome and minitest_chrome once Chrome 60 will be released
# test_script:
#   - bundle exec rake rspec mspec_nodejs minitest_nodejs minitest_node_nodejs
